name: Follett
favicon: null
layout_spectrum: 0.17629
typography_spectrum: 0.53369
title: 'Ken & David Follett'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e2f0fb'
    - '#c7c1c1'
    - '#0d140d'
    - '#687240'
    - '#e04334'
  brandStrength: 0.1875
  lightness: 0.1875
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
