name: Follett
favicon: null
layout_spectrum: 0.83935
typography_spectrum: 0.57822
title: 'Ken & David Follett'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#131112'
    - '#a4aaba'
    - '#96632e'
    - '#f6754e'
    - '#fdfef9'
  brandStrength: 0.625
  lightness: 0.5625
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
