name: Follett
favicon: null
layout_spectrum: 0.83935
typography_spectrum: 0.57822
title: 'Ken & David Follett'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d5dbe7'
    - '#ffffff'
    - '#887a77'
    - '#0d0d0d'
    - '#aaa9af'
  brandStrength: 0.2029692968353629
  lightness: 0.3591422876343131
  saturation: 0.3125
  rhythmicContrast: 0.7315320281777531
purpose: []
