name: Follett
favicon: null
layout_spectrum: 0.8259109572973102
typography_spectrum: 0.15142475860193372
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.2029692968353629
  lightness: 0.3591422876343131
  saturation: 0.18523925752379
  rhythmicContrast: 0.7315320281777531
purpose: []
